package it.eurotn.panjea.rich.editors.update.step;

public enum StepUpdate {
	WAITING, CHECKSUM_PREPARE, CHECKSUM_DOWNLOAD, CHECKSUM_UPLOAD, UPDATE_DOWNLOAD, UPDATE_UPLOAD, APPLY_UPDATE, UPDATE_VERSION, NOT_UPDATE_FILE, UPDATE_FILE_CORRUPTED;
}