package it.eurotn.panjea.contabilita.domain;

/**
 * Rappresenta i tipi di conto base che possono essere selezionati.
 * 
 * @author fattazzo
 * @version 1.0, 27/ago/07
 */
public enum ETipoContoBase {
	ALTRO, CHIUSURA_BILANCIO, APERTURA_BILANCIO, PROFITTI_PERDITE, UTILE, PERDITA, RIEPILOGO, EFFETTI_ATTIVI, ABBUONI_ATTIVI, ABBUONI_PASSIVI, SPESE_INCASSO, SPESE_INSOLUTO, SPESE_PRESENTAZIONE_EFFETTI, ACCONTO_CLIENTE, ACCONTO_FORNITORE, ACCONTO_IVA, SCONTO_FINANZIARIO, PERDITE_CAMBI, UTILE_CAMBI, ERARIO_TEMPORANEO, ERARIO_DA_PAGARE, FONDO_PROFESSIONISTI, QUOTA_INPS, QUOTA_ENASARCO, QUOTA_PREVIDENZIALE_AZIENDA, RATEO_ATTIVO, RATEO_PASSIVO, RISCONTO_ATTIVO, RISCONTO_PASSIVO, ANTICIPI_FATTURE;
}